[package]
name = "broodmap"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
encoding_rs = "0.8"
explode = "0.1"
nom = "7.0"
smallvec = "1.10"
thiserror = "1.0"

[dev-dependencies]
assert_ok = "1.0"
rstest = "0.16"
