[package]
name = "broodmap"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.70"

[dependencies]
bitflags = "2.4"
encoding_rs = "0.8"
explode = "0.1"
nom = "7.1"
smallvec = "1.11"
thiserror = "1.0"

[dev-dependencies]
assert_ok = "1.0"
rstest = "0.18"
