[package]
name = "broodmap"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.3"
encoding_rs = "0.8"
explode = "0.1"
nom = "7.1"
once_cell = "1.17"
smallvec = "1.10"
thiserror = "1.0"

[dev-dependencies]
assert_ok = "1.0"
rstest = "0.16"
